"""Manuscript-ready LaTeX table of the reservoir accounting."""

from __future__ import annotations

import os
from typing import List

from fedcore.atomic_io import atomic_write_text

_HEADER = r"""% Auto-generated by `python -m fedcore.accounting.cli` -- do not hand-edit.
% Distinguishes nominal draws from the distinct labelled examples behind them.
\begin{table}[t]
\centering
\small
\begin{tabular}{llrrrrrr}
\toprule
Dataset & Draw family & Runs & Nominal & Unique & Dup.\ rate & Infl. & Oper.\ labels \\
\midrule
"""

_FOOTER = r"""\bottomrule
\end{tabular}
\caption{Reservoir accounting. \emph{Nominal} is the number of draws taken;
\emph{Unique} the number of distinct labelled examples behind them; \emph{Infl.} is
nominal/unique. The headline certification draw is a permutation of the trusted pool
(without replacement), so its duplication rate is exactly zero and nominal equals
unique; the audit-bootstrap family draws with replacement, where the two diverge.
\emph{Oper.\ labels} counts the distinct trusted labels a deployer must actually
obtain (proposal $+$ certification reservoir), excluding the research-only test fold.}
\label{tab:reservoir-accounting}
\end{table}
"""

_FAMILY = {
    "headline_repartition": "Headline cert.\\ (perm.)",
    "audit_bootstrap": "Audit bootstrap (w/ repl.)",
    "grouped_quota": "Grouped $G{=}2$ quota",
    "grouped_iid_group": "Grouped $G{=}2$ iid",
}


def write_tex_table(summary: List[dict], path: str) -> None:
    """Aggregate the summary rows to one line per (dataset, draw family)."""
    from collections import defaultdict

    agg = defaultdict(lambda: {"runs": set(), "nom": 0, "uni": 0, "op": 0})
    for r in summary:
        # Only the ratio=1.0 bootstrap is the study's operating point; the sweep rows
        # exist for the occupancy figure and would double-count here.
        if r["draw_mode"] == "audit_bootstrap" and not r[
            "certificate_variant"
        ].endswith("_ratio1.0"):
            continue
        a = agg[(r["dataset"], r["draw_mode"])]
        a["runs"].add(r["n_runs"])
        a["nom"] += r["nominal_certification_draws_total"]
        a["uni"] += r["unique_labels_used_in_certification_draw_total"]
        a["op"] += r["operational_unique_trusted_labels_total"]

    lines = []
    for (ds, mode), a in sorted(agg.items()):
        nom, uni = a["nom"], a["uni"]
        dup = 1.0 - uni / nom if nom else 0.0
        infl = nom / uni if uni else float("nan")
        lines.append(
            f"{ds} & {_FAMILY.get(mode, mode)} & {max(a['runs'])} & {nom:,} & {uni:,} & "
            f"{dup:.3f} & {infl:.2f}$\\times$ & {a['op']:,} \\\\"
        )
    atomic_write_text(path, _HEADER + "\n".join(lines) + "\n" + _FOOTER)
